spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  profiles:
    active: pro
  mvc:
    view:
      suffix: .html
      prefix: /
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png